### ISSUE TITLE
master upload to release repo

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/kiwisolver-wheels#1]
Going through the rackspace wheels, I noticed that master was not uploaded to pre-releases but directly to releases. I guess that to fix this I need to re-generate the encoded variables which I cannot do without the security keys of Rackspace. @matthew-brett could you do this or let me know how to proceed ?

**Comment by MatthieuDartiailh** [comment]
@matthew-brett should I try to follow the organization described in the README (one branch per version uploading to the release rackspace, and master to the other one), or not ? Following the README sounds more sound to me but I am not sure how to handle the encoded variables.

**Comment by matthew-brett** [comment]
What I would do, is have the master branch, for building pre-release wheels from your master branch, maybe uploading to the pre-release container, and then have named branches for your release builds.   The key will work as long as you are uploading to that Rackspace account.

See scipy-wheels for an example : https://github.com/MacPython/scipy-wheels/blob/master/.travis.yml

**Comment by MatthieuDartiailh** [comment]
Thanks for the pointer, I will follow your suggestion. Thanks again for the great infrastructure !

**Comment by MatthieuDartiailh** [comment]
This works great. I updated the three repository you set up for me to use this mechanism. And I will soon update the wheels for atom and enaml. Thanks again for your amazing job here.

**Comment by matthew-brett** [comment]
No problem - I'm glad it was useful.

On Tue, Mar 6, 2018 at 8:26 AM, Matthieu Dartiailh <notifications@github.com
