### ISSUE TITLE
Possibility to build ARM wheels

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/kiwisolver-wheels#3]
Hi @matthew-brett,
One user has inquired about wheels for ARM7. Looking at bit online it looks like there are docker image available, so perhaps we could do that using CircleCI. Have you ever looked into doing something similar ?
Best

**Comment by matthew-brett** [comment]
Sorry, no, I haven't looked at that.  It really needs a definition of a 'standard' ARM7 setup, parallel to the standard Intel setup, specified in 'manylinux'. 

You probably already saw this : https://forums.resin.io/t/precompiled-python-wheels-for-arm/591

But the real work that needs doing is some proposal to the Python packaging people about what the base system should be ...

**Comment by MatthieuDartiailh** [comment]
@matthew-brett I got another request for aarch64 wheels (https://github.com/nucleic/kiwi/issues/83). Has there been any progress on stabilizing a wheel format for this kind of platform ?

**Comment by matthew-brett** [comment]
I think this is still to be done - at least - here was the latest I saw on
the matter : https://github.com/pypa/manylinux/issues/84

**Comment by MatthieuDartiailh** [comment]
Indeed looks complicated. I saw mention of aarch in  manylinux2014. Would this be a path worth following ?

**Comment by matthew-brett** [comment]
@mattip  - can I ask for your opinion on this?  Sorry, I haven't been following the aarch64 Manylinux story ...

**Comment by MatthieuDartiailh** [comment]
In particular it seems numpy managed to get wheels for aarch64 (cf https://github.com/pandas-dev/pandas/issues/33971)

**Comment by mattip** [comment]
arm64 or aarch64 is supported by manylinux2014. arm32 in its many different manifestations is not. You can use multibuild to package arm64 wheels (or cibuildwheel).  Here is the [Travis CI snippet](https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml#L58) numpy uses.

**Comment by MatthieuDartiailh** [comment]
Thanks for the pointer @mattip ! I will have a look.

**Comment by MatthieuDartiailh** [comment]
Worked like a charm thanks !
