### ISSUE TITLE
Building on MacOSX for Python 3.8

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/kiwisolver-wheels#5]
I updated multibuild and was able to successfully build on Linux and Windows. However on Mac, Python 3.4 (not a real concern) and 3.8 builds are failing (the others pass).

I have a mac if debugging locally can help, but I will need directions. The error I get is:
```
The directory '/Users/travis/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

installer: Error the package path specified was invalid: 'downloads/python-3.8.0-macosx10.6.pkg'.
```

**Comment by matthew-brett** [comment]
Yes, 3.4 is no longer supported, and you need:

```
MB_PYTHON_OSX_VER=10.9
```

set in your build matrix, for Python 3.8 - see https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml

**Comment by MatthieuDartiailh** [comment]
Thanks @matthew-brett !!! Everything is fine now.
