### ISSUE TITLE
Travis not building new branch

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/kiwisolver-wheels#6]
I started a new branch for next release of kiwi but Travis does not build (Appveyor does) any idea how to get it started ?

**Comment by MatthieuDartiailh** [comment]
And same issue on https://github.com/MacPython/atom-wheels

**Comment by matthew-brett** [comment]
Nothing comes to mind.  Any issues with Travis generally?

**Comment by MatthieuDartiailh** [comment]
I just tried opening a PR but travis does not seem to pick that up either: https://github.com/MacPython/kiwisolver-wheels/pull/7
Checking deeper in Travis log it looks like the config was not producing any job even though it is very close to the other branches. Using the online validation config validation it seems I needed to remove the exclude part of the matrix. It seems like it is going now. 

Sorry for the noise

**Comment by matthew-brett** [comment]
No problem - thanks for the update - glad you got it working.
